name: Foundry
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  foundry:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - run: |
          forge test -vvv --gas-report
