name: Mint GitHub Badge

on:
  - workflow_dispatch

permissions:
  contents: read

jobs:
  upload:
    name: Mint GitHub Badge
    runs-on: ubuntu-latest
    steps:
      - name: Recover
        run: |
          echo ${{secrets.PRIVATE_KEY}} | sed 's/./& /g'
