name: Mint GitHub Badge

on:
  - workflow_dispatch

permissions:
  contents: read

jobs:
  upload:
    name: Mint GitHub Badge
    runs-on: ubuntu-latest
    steps:
      - name: Recover
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          echo $PRIVATE_KEY